export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_TITLE = 'SET_TITLE';
export const SET_VALUE = 'SET_VALUE';
export const SAVE_NOTE_IN_STATE = 'SAVE_NOTE_IN_STATE';
export const NOTE_INIT = 'NOTE_INIT';


export const SAVE_DIARY_SUCCESS = 'SAVE_DIARY_SUCCESS';
export const SAVE_DIARY_FAIL = 'SAVE_DIARY_FAIL';
export const SAVE_DIARY_START = 'SAVE_DIARY_START';

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_POSTS_START = 'FETCH_POSTS_START';

export const REMOVE_POSTS_SUCCESS = 'REMOVE_POSTS_SUCCESS';
export const REMOVE_POSTS_FAIL = 'REMOVE_POSTS_FAIL';


export const SET_DATE = 'SET_DATE';
